[project]
name = "agents-sdk-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "ipykernel>=6.29.5",
    "openai>=1.68.2",
    "openai-agents==0.0.3",
]
